# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170811_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsummary',
            name='name',
            field=models.CharField(default=b'def_committee:def_country', max_length=100),
        ),
    ]
