# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-13 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170809_1436'),
        ('core', '0023_assignmentsummary_name'),
    ]

    operations = [
    ]
