# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20170813_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='assignmentsummary',
            name='name',
        ),
        migrations.AddField(
            model_name='assignmentsummary',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Assignment'),
        ),
        migrations.AlterModelTable(
            name='assignmentsummary',
            table='assignmentsummary',
        ),
    ]
