# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170905_2153'),
        ('core', '0023_assignmentsummary_name'),
    ]

    operations = [
    ]
