# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20170923_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsummary',
            name='name',
            field=models.CharField(default=b'define_committee:define_country', max_length=100),
        ),
    ]
