# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-23 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170923_1603'),
        ('core', '0024_merge_20170813_1421'),
    ]

    operations = [
    ]
